# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-27 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
